---
  host:
    description: "Splunk server"
    type: "string"
    secret: false
    required: true
  port:
    description: "Splunk port (default 8089)"
    type: "integer"
    secret: false
    required: true
    default: 8089
  scheme:
    description: "Protocol used for Splunk API - http or https"
    type: "string"
    secret: false
    required: false
    default: "https"
  verify:
    description: "Check the validity of the SSL certificate returned by Splunk"
    type: "boolean"
    secret: false
    required: false
    default: true
